# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-wait" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "fa8e40d9851a044dcb25100c74c859d2841da16fe4accb8e664241fe539dd2c9"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f54ef754c0d3804371a4b8e133c192eee7a0ff294275621ecd4f4bcdc3af120a"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1b50b44a88f7b3b1c93de1c9861f56b997882eb70a414988c0a679d7f79cdfe"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ba2cb85a15e34d61b3d4c83da596c9aad8580c039abb5ab6619917f63fbe33ab"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Linux_arm64.tar.gz"
    end
  end

  name "slack-wait"
  desc "CLI that waits on Slack conversations and streams messages as NDJSON"
  homepage "https://github.com/uji/slack-wait"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-wait"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack-wait"]
    end
  end

  # No zap stanza required

end
