# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-wait" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "de4940d21fc19648f61525d619adf03ea3749e30cf9690982e6f214db826b7ca"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6dfe9e4226bbe131d07383b8d65d56a9e25a9544bda40c61e90f6f1126c2bf35"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f1d7987fd025a8367d3b1fc7617be1a64674c91b176c9e9abbc075bb777f8fc0"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "fe9643ca3f2277a991fd669f9b5e32dd9666d79f323948a2d1ef3492324c2318"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Linux_arm64.tar.gz"
    end
  end

  name "slack-wait"
  desc "CLI that waits on Slack conversations and streams messages as NDJSON"
  homepage "https://github.com/uji/slack-wait"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-wait"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack-wait"]
    end
  end

  # No zap stanza required

end
