# This file was generated by GoReleaser. DO NOT EDIT.
cask "slack-wait" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "64635da324c43c4d364e5485e88e008ed98b07e5d60890be2a223548e288e1c1"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "84e1c5a28b415515c7a9e52f5d020ab5d9e3188b3092446388597e1b90ec4eab"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4699846edf77bae79dd2ecb81a4fc67ae8b26c0e6062d4f381ff40be3ae8e5ca"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c61ca0441d661c90332e90d665ffcf09806fb234f3546a9c8b5f98e73bc26fc9"
      url "https://github.com/uji/slack-wait/releases/download/v#{version}/slack-wait_Linux_arm64.tar.gz"
    end
  end

  name "slack-wait"
  desc "CLI that waits on Slack conversations and streams messages as NDJSON"
  homepage "https://github.com/uji/slack-wait"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slack-wait"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slack-wait"]
    end
  end

  # No zap stanza required

end
